language: python

python:
  - 3.6

services:
  - postgresql

before_install:
  - pip install peewee psycopg2-binary cython

install:
  - pip install .

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python setup.py bdist_egg bdist_wheel --universal sdist --formats=zip
  - python -m unittest --verbose --locals tests.TestFields


notifications:
  email:
    recipients: juancarlospaco@gmail.com
    on_success: change
    on_failure: always

cache:
  apt: true
  pip: true

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.6
